#!/bin/bash
AUTHOR="Sven Rouvinez"
DIRECTORY="convert"


while getopts ":a:" optname
do
   case "$optname" in
   "a")
      AUTHOR="$OPTARG"
   ;;

   *)
      echo "false parameters"
   ;;
   esac
done


if [ ! -d "$DIRECTORY" ]; then
   mkdir $DIRECTORY
fi

for f in *.h *.cpp
do
echo "
\documentclass[a4paper,9pt]{article}

\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage[usenames,dvipsnames]{color}  %% Allow color names
\usepackage{pxfonts}
\usepackage{textcomp}

\pagestyle{fancy}
\setlength\headheight{26pt}


%% Path to file, just change this one 
\newcommand{\pathcodefile}{"$f"}
\fancyheadoffset[L]{2cm}
\fancyhead[RO]{\footnotesize\textbf{$AUTHOR - INF1-C - HEIG-VD}}
\fancyhead[LO]{\includegraphics[width=50px]{/opt/src2pdf/heigvdBW.png}\footnotesize\textbf{\pathcodefile}}

   \definecolor{lightGray}{rgb}{0.66,0.66,0.66}
      \definecolor{heavyGray}{rgb}{0.44,0.44,0.44}
         \definecolor{Charcoal}{rgb}{0.21,0.27,0.31}


            
         %% The listings package will format your source code
         \usepackage{listings}
         \lstdefinestyle{customasm}{
              belowcaptionskip=1\baselineskip,
                   xleftmargin=\parindent,
                     language=C++,
                       breaklines=true, %% Wrap long lines
                            basicstyle=\footnotesize\ttfamily,
                         commentstyle=\itshape\color{lightGray},
                           stringstyle=\color{heavyGray},
                             keywordstyle=\bfseries\color{black},
                               identifierstyle=\color{Charcoal},
                                 inputencoding=utf8,
                                   extendedchars=true,
                                     literate={à}{{\`a}}1 {á}{{\'a}}1 {ã}{{\~a}}1 {é}{{\'e}}1,
                                       xleftmargin=-8em,
                                         showstringspaces=false
         }        
\begin{document}


\lstinputlisting[style=customasm]{\pathcodefile}

\end{document}" | pdflatex  -output-directory=$DIRECTORY -jobname=$f
done
