#!/bin/bash
#Authors: Sven Roubinez, Yohann Meyer
#
# This script convert a source file in C++
# to pdf with the syntaxic coloration wanted by
# Mr. Breguet for his course INF1.
#
# Use this script with two parameters.
# $1: path to source file
# $2: Name or number of the lab
echo "
\documentclass[a4paper,9pt]{article}

\usepackage[utf8]{inputenc}
\usepackage{fancyhdr}
\pagestyle{fancy}


%% Path to file, just change this one 
\newcommand{\pathcodefile}{"$1"}

\fancyhead[RO]{\footnotesize\textbf{Yohann Meyer - INF1-C - HEIG-VD }}
\fancyhead[LO]{\footnotesize\textbf{\pathcodefile}}
\usepackage[usenames,dvipsnames]{color}  %% Allow color names
\usepackage{pxfonts}
\usepackage{textcomp}


   \definecolor{lightGray}{rgb}{0.66,0.66,0.66}
      \definecolor{heavyGray}{rgb}{0.44,0.44,0.44}
         \definecolor{Charcoal}{rgb}{0.21,0.27,0.31}


            
         %% The listings package will format your source code
         \usepackage{listings}
         \lstdefinestyle{customasm}{
              belowcaptionskip=1\baselineskip,
                   xleftmargin=\parindent,
                     language=C++,
                       breaklines=true, %% Wrap long lines
                            basicstyle=\footnotesize\ttfamily,
                         commentstyle=\itshape\color{lightGray},
                           stringstyle=\color{heavyGray},
                             keywordstyle=\bfseries\color{black},
                               identifierstyle=\color{Charcoal},
                                 inputencoding=utf8,
                                   extendedchars=true,
                                     literate={à}{{\`a}}1 {á}{{\'a}}1 {ã}{{\~a}}1 {é}{{\'e}}1,
                                       xleftmargin=-8em,
                                         showstringspaces=false
         }        
\begin{document}


\lstinputlisting[style=customasm]{\pathcodefile}

\end{document}" | pdflatex -jobname=Labo"$2"
